modLoader="javafml"
loaderVersion="[4,)"
license="Copyright (c) 2026 JoltTheWolf, SPDX-License-Identifier: LicenseRef-Cobblemon-Armory"

[[mods]]
modId="cobblemonarmory"
version="1.5.2"
displayName="Cobblemon: Armory"
authors="JoltTheWolf"
description='''
Cobblemon: Armory is an add-on for the Cobblemon mod that lets you craft armor and weapons based on your favorite Cobblemon.
'''
curseforge="https://www.curseforge.com/minecraft/mc-mods/cobblemon-armory"
modrinth="https://modrinth.com/mod/cobblemon-armory"
sources="https://github.com/JoltTheWolf/Cobblemon-Armory"
discord="https://discord.gg/Wph4w8vEkw"

[[dependencies.cobblemonarmory]]
modId="neoforge"
type="required"
versionRange="[21.1.220,)"
ordering="NONE"
side="BOTH"

[[dependencies.cobblemonarmory]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.cobblemonarmory]]
modId="geckolib"
type="required"
versionRange="[4.7.7,)"
ordering="NONE"
side="BOTH"